# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'f966e346-3d7d-474c-8586-206a3873f081'
  imageRepository: 'voteapp'
  containerRegistry: 'votingappcicddemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
#  vmImageName: 'ubuntu-latest'
pool:
 name: azurecicdagent

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: azurecicdagent
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'

  - job: Push
    displayName: Push
    pool:
      name: azurecicdagent
    steps:
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'    
- stage: Update
  displayName: Update stage
  jobs:
  - job: update
    displayName: update
    pool:
      name: azurecicdagent
    steps:  
    - task: ShellScript@2
      inputs:
             scriptPath: 'scripts/updateK8smanifest.sh'
             args: 'vote $imageRepository $tag'